sonar.projectKey=2iAcademy_rekr-app
sonar.organization=2iacademy
sonar.projectName=Rekr

sonar.sources=backend/src,clientApp/src

sonar.tests=backend/src,clientApp/src,backend/test
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/*.e2e-spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/generated/**,**/coverage/**,**/*.config.ts,**/*.config.js,**/*.config.mjs

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,clientApp/coverage/lcov.info
