import type { FeedOffer } from './types';

// No endpoint lists swipeable offers yet (#135). These deterministic mocks cover
// every candidate filter and keep the feed usable without a backend dependency.
export const mockFeedOffers: readonly FeedOffer[] = [
  {
    id: 101,
    title: 'Développeur Frontend React',
    companyName: 'Acme Studio',
    companyLogoUrl: null,
    companySize: 'PME',
    city: 'Lyon',
    contractType: 'CDI',
    remotePolicy: 'HYBRID',
    stack: ['React', 'TypeScript', 'Tailwind'],
    salaryMin: 42000,
    salaryMax: 50000,
    description:
      'Rejoins une équipe produit qui construit des outils simples pour les équipes terrain.',
  },
  {
    id: 102,
    title: 'Data Analyst',
    companyName: 'Nova Data',
    companyLogoUrl: null,
    companySize: 'PME',
    city: 'Paris',
    contractType: 'CDI',
    remotePolicy: 'FULL_REMOTE',
    stack: ['SQL', 'dbt', 'Power BI'],
    salaryMin: 40000,
    salaryMax: 47000,
    description: 'Transforme les données produit en décisions utiles pour les équipes métier.',
  },
  {
    id: 103,
    title: 'Développeur Full-Stack',
    companyName: 'Mistral Labs',
    companyLogoUrl: null,
    companySize: 'TPE',
    city: 'Grenoble',
    contractType: 'CDD',
    remotePolicy: 'ON_SITE',
    stack: ['NestJS', 'PostgreSQL', 'Vue.js'],
    salaryMin: 38000,
    salaryMax: 45000,
    description:
      "Participe à la création d'une plateforme B2B du prototype à la mise en production.",
  },
  {
    id: 104,
    title: 'Product Designer',
    companyName: 'Bloom',
    companyLogoUrl: null,
    companySize: 'PME',
    city: 'Lyon',
    contractType: 'FREELANCE',
    remotePolicy: 'HYBRID',
    stack: ['Figma', 'Design system', 'Recherche utilisateur'],
    salaryMin: null,
    salaryMax: 65000,
    description: 'Conçois un produit santé inclusif avec une équipe pluridisciplinaire.',
  },
  {
    id: 105,
    title: 'DevOps Engineer',
    companyName: 'Carbon Cloud',
    companyLogoUrl: null,
    companySize: 'PME',
    city: 'Annecy',
    contractType: 'CDI',
    remotePolicy: 'FULL_REMOTE',
    stack: ['Kubernetes', 'Terraform', 'GitHub Actions'],
    salaryMin: 52000,
    salaryMax: 60000,
    description: 'Industrialise les déploiements et accompagne les développeurs dans le cloud.',
  },
  {
    id: 106,
    title: 'Développeur Mobile',
    companyName: 'Triflod',
    companyLogoUrl: null,
    companySize: 'TPE',
    city: 'Villeurbanne',
    contractType: 'ALTERNANCE',
    remotePolicy: 'ON_SITE',
    stack: ['Flutter', 'Dart', 'Firebase'],
    salaryMin: null,
    salaryMax: null,
    description:
      'Développe une application mobile déjà utilisée par plusieurs milliers de personnes.',
  },
  {
    id: 107,
    title: 'Ingénieur Backend Java',
    companyName: 'Atlas',
    companyLogoUrl: null,
    companySize: 'PME',
    city: 'Chambéry',
    contractType: 'STAGE',
    remotePolicy: 'HYBRID',
    stack: ['Java', 'Spring Boot', 'Kafka'],
    salaryMin: null,
    salaryMax: null,
    description: 'Découvre un environnement exigeant et contribue à des services à fort volume.',
  },
  {
    id: 108,
    title: 'Chef de projet digital',
    companyName: 'Volt Conseil',
    companyLogoUrl: null,
    companySize: 'PME',
    city: 'Paris',
    contractType: 'INTERIM',
    remotePolicy: 'ON_SITE',
    stack: ['Agile', 'Jira', 'Conduite du changement'],
    salaryMin: 36000,
    salaryMax: 42000,
    description: 'Pilote des projets de transformation numérique chez nos clients.',
  },
];
