#!/usr/bin/env bash
# The only program the `deploy` account can run on the server. Its SSH key is
# pinned to this script in ~deploy/.ssh/authorized_keys:
#
#   restrict,command="/opt/rekr/scripts/deploy/remote-deploy.sh" ssh-ed25519 …
#
# so whatever a connection asks for lands here, in SSH_ORIGINAL_COMMAND, and
# the only request accepted is `deploy <40-hex commit>`. The production `.env`
# comes in on standard input, generated by .github/workflows/deploy.yml from
# the GitHub `production` environment: nobody edits it by hand on the server.
#
# The commit must be on origin/main. A leaked key can therefore only redeploy
# code that was already reviewed and merged, never a branch of its own.
set -euo pipefail

REPO_DIR="${REKR_REPO_DIR:-/opt/rekr}"
DEPLOY_BRANCH=main
# The checkout is shared with the administrators through the `docker` group
# (docs/deploiement-vps.md): what this script writes stays group-writable.
SHARED_GROUP="${REKR_SHARED_GROUP:-docker}"
umask 002
# A real .env is a few kilobytes; anything far bigger is not one.
MAX_ENV_BYTES=65536

fail() {
  echo "remote-deploy: $*" >&2
  exit 1
}

read -r action sha extra <<<"${SSH_ORIGINAL_COMMAND:-}" || true
[[ "${action:-}" == deploy ]] || fail "expected 'deploy <commit>'"
[[ -z "${extra:-}" ]] || fail "unexpected arguments"
[[ "${sha:-}" =~ ^[0-9a-f]{40}$ ]] || fail "expected a full 40-character commit hash"

cd "$REPO_DIR"

git fetch --quiet origin "$DEPLOY_BRANCH"
git merge-base --is-ancestor "$sha" "origin/$DEPLOY_BRANCH" 2>/dev/null ||
  fail "commit $sha is not on origin/$DEPLOY_BRANCH"

# Written next to its final place, then renamed over it: a deploy cut short
# leaves the previous .env whole, never a half-written one. Group-readable so
# that the administrators, also in the `docker` group, can read it.
env_tmp="$(mktemp "$REPO_DIR/.env.XXXXXX")"
trap 'rm -f "$env_tmp"' EXIT
head -c "$((MAX_ENV_BYTES + 1))" >"$env_tmp"
env_size="$(wc -c <"$env_tmp")"
((env_size > 0)) || fail "no .env received on standard input"
((env_size <= MAX_ENV_BYTES)) || fail ".env larger than $MAX_ENV_BYTES bytes"
chgrp "$SHARED_GROUP" "$env_tmp"
chmod 640 "$env_tmp"
mv -f "$env_tmp" "$REPO_DIR/.env"
trap - EXIT

git checkout --quiet --detach "$sha"

docker compose -f compose.prod.yml up -d --build --remove-orphans
# The server has a small disk: drop the images each build leaves dangling.
docker image prune -f >/dev/null

echo "remote-deploy: $sha deployed"
