/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Rekr API
 * API documentation for the Rekr backend
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from './customFetch';
export interface PublishErrorLogDto {
  [key: string]: unknown;
}

export type SignupDtoUserType = (typeof SignupDtoUserType)[keyof typeof SignupDtoUserType];

export const SignupDtoUserType = {
  candidate: 'candidate',
  recruiter: 'recruiter',
} as const;

export interface SignupDto {
  email: string;
  /**
   * @minLength 8
   * @maxLength 512
   */
  password: string;
  userType: SignupDtoUserType;
}

export interface LoginDto {
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface CreateCandidateProfileDto {
  [key: string]: unknown;
}

export interface UpdateCandidateProfileDto {
  [key: string]: unknown;
}

export interface CreateCompanyDto {
  [key: string]: unknown;
}

export interface UpdateCompanyDto {
  [key: string]: unknown;
}

export interface CreateOfferDto {
  [key: string]: unknown;
}

export interface UpdateOfferDto {
  [key: string]: unknown;
}

export interface SectorDto {
  id: number;
  /** @maxLength 100 */
  label: string;
}

export type appControllerGetHelloResponse200 = {
  data: void;
  status: 200;
};

export type appControllerGetHelloResponseSuccess = appControllerGetHelloResponse200 & {
  headers: Headers;
};
export const getAppControllerGetHelloUrl = () => {
  return `/api`;
};

export const appControllerGetHello = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<appControllerGetHelloResponseSuccess> => {
  return customFetch<appControllerGetHelloResponseSuccess>(getAppControllerGetHelloUrl(), {
    ...options,
    method: 'GET',
  });
};

export type appControllerGetErrorResponse200 = {
  data: void;
  status: 200;
};

export type appControllerGetErrorResponseSuccess = appControllerGetErrorResponse200 & {
  headers: Headers;
};
export const getAppControllerGetErrorUrl = () => {
  return `/api/debug-sentry`;
};

export const appControllerGetError = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<appControllerGetErrorResponseSuccess> => {
  return customFetch<appControllerGetErrorResponseSuccess>(getAppControllerGetErrorUrl(), {
    ...options,
    method: 'GET',
  });
};

export type logsControllerPublishSampleResponse202 = {
  data: void;
  status: 202;
};

export type logsControllerPublishSampleResponseSuccess = logsControllerPublishSampleResponse202 & {
  headers: Headers;
};
export const getLogsControllerPublishSampleUrl = () => {
  return `/api/logs/sample`;
};

export const logsControllerPublishSample = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<logsControllerPublishSampleResponseSuccess> => {
  return customFetch<logsControllerPublishSampleResponseSuccess>(
    getLogsControllerPublishSampleUrl(),
    {
      ...options,
      method: 'POST',
    },
  );
};

export type logsControllerPublishErrorResponse202 = {
  data: void;
  status: 202;
};

export type logsControllerPublishErrorResponseSuccess = logsControllerPublishErrorResponse202 & {
  headers: Headers;
};
export const getLogsControllerPublishErrorUrl = () => {
  return `/api/logs/error`;
};

export const logsControllerPublishError = async (
  publishErrorLogDto: PublishErrorLogDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<logsControllerPublishErrorResponseSuccess> => {
  return customFetch<logsControllerPublishErrorResponseSuccess>(
    getLogsControllerPublishErrorUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(publishErrorLogDto),
    },
  );
};

export type authControllerSignupResponse201 = {
  data: void;
  status: 201;
};

export type authControllerSignupResponseSuccess = authControllerSignupResponse201 & {
  headers: Headers;
};
export const getAuthControllerSignupUrl = () => {
  return `/api/auth/signup`;
};

export const authControllerSignup = async (
  signupDto: SignupDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<authControllerSignupResponseSuccess> => {
  return customFetch<authControllerSignupResponseSuccess>(getAuthControllerSignupUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(signupDto),
  });
};

export type authControllerLoginResponse200 = {
  data: void;
  status: 200;
};

export type authControllerLoginResponseSuccess = authControllerLoginResponse200 & {
  headers: Headers;
};
export const getAuthControllerLoginUrl = () => {
  return `/api/auth/login`;
};

export const authControllerLogin = async (
  loginDto: LoginDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<authControllerLoginResponseSuccess> => {
  return customFetch<authControllerLoginResponseSuccess>(getAuthControllerLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto),
  });
};

export type authControllerRefreshResponse200 = {
  data: void;
  status: 200;
};

export type authControllerRefreshResponseSuccess = authControllerRefreshResponse200 & {
  headers: Headers;
};
export const getAuthControllerRefreshUrl = () => {
  return `/api/auth/refresh`;
};

export const authControllerRefresh = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<authControllerRefreshResponseSuccess> => {
  return customFetch<authControllerRefreshResponseSuccess>(getAuthControllerRefreshUrl(), {
    ...options,
    method: 'POST',
  });
};

export type authControllerLogoutResponse204 = {
  data: void;
  status: 204;
};

export type authControllerLogoutResponseSuccess = authControllerLogoutResponse204 & {
  headers: Headers;
};
export const getAuthControllerLogoutUrl = () => {
  return `/api/auth/logout`;
};

export const authControllerLogout = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<authControllerLogoutResponseSuccess> => {
  return customFetch<authControllerLogoutResponseSuccess>(getAuthControllerLogoutUrl(), {
    ...options,
    method: 'POST',
  });
};

export type authControllerMeResponse200 = {
  data: void;
  status: 200;
};

export type authControllerMeResponseSuccess = authControllerMeResponse200 & {
  headers: Headers;
};
export const getAuthControllerMeUrl = () => {
  return `/api/auth/me`;
};

export const authControllerMe = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<authControllerMeResponseSuccess> => {
  return customFetch<authControllerMeResponseSuccess>(getAuthControllerMeUrl(), {
    ...options,
    method: 'GET',
  });
};

export type candidateProfileControllerCreateResponse201 = {
  data: void;
  status: 201;
};

export type candidateProfileControllerCreateResponseSuccess =
  candidateProfileControllerCreateResponse201 & {
    headers: Headers;
  };
export const getCandidateProfileControllerCreateUrl = () => {
  return `/api/candidate-profiles`;
};

export const candidateProfileControllerCreate = async (
  createCandidateProfileDto: CreateCandidateProfileDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<candidateProfileControllerCreateResponseSuccess> => {
  return customFetch<candidateProfileControllerCreateResponseSuccess>(
    getCandidateProfileControllerCreateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createCandidateProfileDto),
    },
  );
};

export type candidateProfileControllerUpdateResponse200 = {
  data: void;
  status: 200;
};

export type candidateProfileControllerUpdateResponseSuccess =
  candidateProfileControllerUpdateResponse200 & {
    headers: Headers;
  };
export const getCandidateProfileControllerUpdateUrl = () => {
  return `/api/candidate-profiles/me`;
};

export const candidateProfileControllerUpdate = async (
  updateCandidateProfileDto: UpdateCandidateProfileDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<candidateProfileControllerUpdateResponseSuccess> => {
  return customFetch<candidateProfileControllerUpdateResponseSuccess>(
    getCandidateProfileControllerUpdateUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateCandidateProfileDto),
    },
  );
};

export type companyControllerCreateResponse201 = {
  data: void;
  status: 201;
};

export type companyControllerCreateResponseSuccess = companyControllerCreateResponse201 & {
  headers: Headers;
};
export const getCompanyControllerCreateUrl = () => {
  return `/api/companies`;
};

export const companyControllerCreate = async (
  createCompanyDto: CreateCompanyDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<companyControllerCreateResponseSuccess> => {
  return customFetch<companyControllerCreateResponseSuccess>(getCompanyControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCompanyDto),
  });
};

export type companyControllerUpdateMineResponse200 = {
  data: void;
  status: 200;
};

export type companyControllerUpdateMineResponseSuccess = companyControllerUpdateMineResponse200 & {
  headers: Headers;
};
export const getCompanyControllerUpdateMineUrl = () => {
  return `/api/companies/mine`;
};

export const companyControllerUpdateMine = async (
  updateCompanyDto: UpdateCompanyDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<companyControllerUpdateMineResponseSuccess> => {
  return customFetch<companyControllerUpdateMineResponseSuccess>(
    getCompanyControllerUpdateMineUrl(),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateCompanyDto),
    },
  );
};

export type offerControllerFindOneByIdResponse200 = {
  data: void;
  status: 200;
};

export type offerControllerFindOneByIdResponseSuccess = offerControllerFindOneByIdResponse200 & {
  headers: Headers;
};
export const getOfferControllerFindOneByIdUrl = (id: number) => {
  return `/api/offers/${id}`;
};

export const offerControllerFindOneById = async (
  id: number,
  options?: Parameters<typeof customFetch>[1],
): Promise<offerControllerFindOneByIdResponseSuccess> => {
  return customFetch<offerControllerFindOneByIdResponseSuccess>(
    getOfferControllerFindOneByIdUrl(id),
    {
      ...options,
      method: 'GET',
    },
  );
};

export type offerControllerUpdateResponse200 = {
  data: void;
  status: 200;
};

export type offerControllerUpdateResponseSuccess = offerControllerUpdateResponse200 & {
  headers: Headers;
};
export const getOfferControllerUpdateUrl = (id: number) => {
  return `/api/offers/${id}`;
};

export const offerControllerUpdate = async (
  id: number,
  updateOfferDto: UpdateOfferDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<offerControllerUpdateResponseSuccess> => {
  return customFetch<offerControllerUpdateResponseSuccess>(getOfferControllerUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateOfferDto),
  });
};

export type offerControllerCreateResponse201 = {
  data: void;
  status: 201;
};

export type offerControllerCreateResponseSuccess = offerControllerCreateResponse201 & {
  headers: Headers;
};
export const getOfferControllerCreateUrl = () => {
  return `/api/offers`;
};

export const offerControllerCreate = async (
  createOfferDto: CreateOfferDto,
  options?: Parameters<typeof customFetch>[1],
): Promise<offerControllerCreateResponseSuccess> => {
  return customFetch<offerControllerCreateResponseSuccess>(getOfferControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOfferDto),
export type sectorControllerFindAllResponse200 = {
  data: SectorDto[];
  status: 200;
};

export type sectorControllerFindAllResponseSuccess = sectorControllerFindAllResponse200 & {
  headers: Headers;
};
export const getSectorControllerFindAllUrl = () => {
  return `/api/sectors`;
};

export const sectorControllerFindAll = async (
  options?: Parameters<typeof customFetch>[1],
): Promise<sectorControllerFindAllResponseSuccess> => {
  return customFetch<sectorControllerFindAllResponseSuccess>(getSectorControllerFindAllUrl(), {
    ...options,
    method: 'GET',
  });
};
